language: ruby
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails_4_2_x.gemfile
  - gemfiles/rails_5_0_x.gemfile
  - gemfiles/rails_5_1_x.gemfile
  - gemfiles/rails_5_2_x.gemfile
