language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1.3
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails_3_2_x.gemfile
  - gemfiles/rails_4_0_x.gemfile
  - gemfiles/rails_4_1_x.gemfile
  - gemfiles/rails_4_2_x.gemfile
  - gemfiles/rails_5_0_x.gemfile
  - gemfiles/rails_5_1_x.gemfile
  - gemfiles/rails_5_2_x.gemfile
